apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.ServiceNameLower}}-deployment
  labels:
    app: {{.ServiceNameLower}}
spec:
  selector:
    matchLabels:
      app: {{.ServiceNameLower}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.ServiceNameLower}}
    spec:
      containers:
        - name: {{.ProtocolServiceNameLower}}
          image: docker.io/dev/{{.ServiceNameLower}}:latest
          imagePullPolicy: Never  # or IfNotPresent
          ports:
            - containerPort: 9992
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{.ServiceNameLower}}-svc
spec:
  type: NodePort
  selector:
    app: {{.ServiceNameLower}}
  ports:
    - protocol: TCP
      nodePort: 30002
      targetPort: 9992
      port: 9992
